apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
  labels:
    app: cloud-config-server
    demo: spring-cloud-config-demo
spec:
  ports:
    - port: 8888
      protocol: TCP
  selector:
    app: cloud-config-server