= Spring Cloud Demos -  Spring Cloud Config Server/Client

images::images/config-server.png

Two main projects:

- link:cloud-config-server/[Cloud Config Server]. A simple Spring Cloud App. This apps shows you the usage of the `@EnableConfigServer` annotation. Is necessary to provide a Git Server.
- link:cloud-config-client/[Cloud Config Client]. A simple Spring Cloud Client. It reaches out for the Config Server and gets ints configuration from the Git Server.


== Local Deployment

There is already version `0.0.1` of these apps in https://quay.io/repository/[Quay.io].

You can get the images to your local environment with:

- `docker pull quay.io/felipeg/demo-config-server:0.0.1`
- `docker pull quay.io/felipeg/demo-config-client:0.0.1`

You can run them locally with:
[source,shell]
----
docker run -d --name config-server --rm \
 -p 8888:8888 \
 quay.io/felipeg/demo-config-server:0.0.1

docker run -d --name config-client --rm \
 -p 8080:8080 \
 quay.io/felipeg/demo-config-client:0.0.1
----

== OpenShift Deployment

On each project there are `YAML` files that contain all the necessary declaration to deploy the server and the client.
If you clone this repo, you can do:
. Create a Project
+
[source,shell]
----
oc new-project spring-cloud-demos \
 --description="These are Spring Cloud Demos on OpenShift" \
 --display-name="spring-cloud-demos"
----
. Deploy the Server with:
+
[source,shell]
----
oc create -f cloud-config-server/
----
. Deploy the Client with:
+
[source,shell]
----
oc create -f cloud-config-client/
----
. Take a look at the Route with:
+
[source,shell]
----
oc get route -l app=cloud-config-client
----

== Remove/Delete
[source,shell]
----
oc delete all -l demo=spring-cloud-config-demo
----